server:
  port: 8080

database:
  host: localhost
  port: 3306
  user: your_username
  password: your_password
  name: dtxcasemgnt

log:
  level: info
  format: json

jwt:
  secret: your_jwt_secret
  expiration: 24h