server:
  port: 8080

database:
  host: localhost
  port: 5432
  user: your_username
  password: your_password
  name: your_database_name

log:
  level: info
  format: json

jwt:
  secret: your_jwt_secret
  expiration: 24h